language: ruby
cache: bundler
bundler_args: "--without production"
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- rake db:migrate RAILS_ENV=test
notifications:
  slack:
    secure: OixL+deBxFfKx8ORQSIOufPzcMfsoGN572D4MMDuV7qWLFEHQ33WWR+6pbTyTaYn5XtA4tWxD0QtCy3pZbHBS/M9bJjMzOF1wq8aIk63cgL/SZfFrqorQeGc5iaKPce3BK2x+LUES06pQsRR8N3PpXnCO/pAqqCmaO9vjQHW+86aLK4GJxDZqzj7d96/3rP9CWSoM/gYTWmXUR3riDofcAky8QId1wR6nNMk6Nrgw0iHgzRC5s2fvg72KetWI7Dt7oDKsMwMCjy7pk0gIAWNqpapKhYLrwWvrvaCrgbcW8R40J7Uq4jvgrhZGGBVS7IaQz+7gCRgRPRZl8l+6r0PYWv2ETw1gmyn7oA/C7UUD37jAJhCIYg256YM8zjh2WR79Kfvz20jBnjlArjIZzM/KHF6G0UBvwn+JBhL1Z54BKgVMZiKKdnqtGoJPmJw9PslNX3NEZVrFsYtgzb434hcRyixJtp2mTAVrW01jt7bzz/RUlGkIvwepjwyVxTWHCyJp2rRHqmRP7R6sSUTa9qYHXL9FGDK5sa7TYLNjPdxtSicLpDlBIDic3wrOrcaKKpWgIphC8Rw2nLxFU3rvLDUCihi8quOvrIAL/RW7FY0HcUycu8LiNm2DNuHF2rXihUYrakLUdC6TgibtIWySTq1cjJPMg1djOdS+Q8AXnm5UGE=
deploy:
  provider: heroku
  app: polar-crag-81448
  api_key:
    secure: c0kxqjLclbkJNKO7zdIHSPc6s6/YiW67MlqnslEpLKWV/KcSKgB6ucF0GOkT3CqcgXXY4lk0p2hgBGesgE6BRZUm7du6qPG8bHiMZkD7rbv3WSRsm1ow6COf9KOvBjCqdmLETZEqJ0cpWxZX9iNMcYciVIQsNIx0mu9+8cWchkfqpLFoliVML7pzbaewjIJZRRjdvZzfG0knL7B+aValw2fZBVnqvrc7zkiAmqsnhjLPJCojUD7++UJjTv477JoBlGBPbk5E+o8NFImFdiPcWZzIHQEoGZm4fMGbTVLHsA+/u5nHwTaCt7IAyDYUPF58peB/a9ocXlDGVSKf6OrvVEpLF1YFoogZOHdBAzyFoCROkWKWVm+rVMo2dFK56/lmaH7+/PEka+k6poRVlZISVO/xtwB/lAeyPLGCoDUeEHuKQB9iLmvIDD8gyBy5Bf6SP1TOtVbmAHUV3r2Ch/HNxSYwUGbPZI+DtM/prAZGsxSKnXZYEl3aTbr30Pc79Vlspf9BdzGrx2ywwu/td0NRNb13gsfR5X3gsA32aHtNSqMTJB6QDWeWgvk/AyNqy3pq2ie7SZ0dntQjavbkjTnMvy+Sf3AjLleVsOpDlYLS6LovlfD3jRIZZ6Eva0PaMAqwQhwRY9KnK3HZskQh5y9bQPJKWTU1MAlL1hn0A8WZQek=
