:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other names
    - :name: universe_id
      :label: Universe
:points_of_interest:
  :label: Points of interest
  :icon: location_on
  :attributes:
    - :name: locations
      :label: Locations
    - :name: towns
      :label: Towns
    - :name: landmarks
      :label: Landmarks
:culture:
  :label: Culture
  :icon: face
  :attributes:
    - :name: population
      :label: Population
    - :name: currency
      :label: Currency
    - :name: laws
      :label: Laws
    - :name: sports
      :label: Sports
    - :name: languages
      :label: Languages
    - :name: religions
      :label: Religions
:geography:
  :label: Geography
  :icon: terrain
  :attributes:
    - :name: area
      :label: Area
    - :name: crops
      :label: Crops
    - :name: climate
      :label: Climate
    - :name: creatures
      :label: Creatures
    - :name: floras
      :label: Flora
:history:
  :label: History
  :icon: timeline
  :attributes:
    - :name: founding_story
      :label: Founding story
    - :name: established_year
      :label: Established year
    - :name: notable_wars
      :label: Notable wars
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
