:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: aliases
      :label: Other names
    - :name: universe_id
      :label: Universe
:classification:
  :label: Classification
  :icon: bubble_chart
  :attributes:
    - :name: order
      :label: Order
    - :name: family
      :label: Family
    - :name: genus
      :label: Genus
:appearance:
  :label: Appearance
  :icon: local_florist
  :attributes:
    - :name: colorings
      :label: Colorings
    - :name: size
      :label: Size
    - :name: smell
      :label: Smell
    - :name: taste
      :label: Taste
:produce:
  :label: Produce
  :icon: add_box
  :attributes:
    - :name: fruits
      :label: Fruits
    - :name: seeds
      :label: Seeds
    - :name: nuts
      :label: Nuts
    - :name: berries
      :label: Berries
    - :name: medicinal_purposes
      :label: Medicinal purposes
:ecosystem:
  :label: ecosystem
  :icon: language
  :attributes:
    - :name: reproduction
      :label: Reproduction
    - :name: seasonality
      :label: Seasonality
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
