:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
      :field_type: name
    - :name: description
      :label: Description
    - :name: type_of_food
      :label: Type of food
    - :name: other_names
      :label: Other names
    - :name: universe_id
      :label: Universe
      :field_type: universe
    - :name:
      :label: Tags
      :field_type: tags
:sales:
  :label: Sales
  :icon: room_service
  :attributes:
    - :name: cost
      :label: Cost
    - :name: sold_by
      :label: Sold by
    - :name: rarity
      :label: Rarity
:recipe:
  :label: Recipe
  :icon: kitchen
  :attributes:
    - :name: ingredients
      :label: Ingredients
    - :name: preparation
      :label: Preparation
    - :name: cooking_method
      :label: Cooking method
    - :name: yield
      :label: Yield
    - :name: color
      :label: Color
    - :name: size
      :label: Size
    - :name: smell
      :label: Smell
    - :name: variations
      :label: Variations
:eating:
  :label: Eating
  :icon: restaurant
  :attributes:
    - :name: serving
      :label: Serving
    - :name: utensils_needed
      :label: Utensils needed
    - :name: texture
      :label: Texture
    - :name: scent
      :label: Scent
    - :name: flavor
      :label: Flavor
:effects:
  :label: Effects
  :icon: cake
  :attributes:
    - :name: nutrition
      :label: Nutrition
    - :name: conditions
      :label: Conditions
    - :name: side_effects
      :label: Side effects
:history:
  :label: History
  :icon: history
  :attributes:
    - :name: place_of_origin
      :label: Place of origin
    - :name: origin_story
      :label: Origin story
    - :name: traditions
      :label: Traditions
    - :name: symbolisms
      :label: Symbolisms
    - :name: related_foods
      :label: Related foods
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
    