:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other names
    - :name: universe_id
      :label: Universe
:hierarchy:
  :label: Hierarchy
  :icon: call_split
  :attributes:
    - :name: organization_structure
      :label: Organization structure
    - :name: leaders
      :label: Leaders
    - :name: members
      :label: Members
    - :name: supergroups
      :label: Supergroups
    - :name: subgroups
      :label: Subgroups
    - :name: sistergroups
      :label: Sistergroups
:locations:
  :label: Locations
  :icon: location_on
  :attributes:
    - :name: locations
      :label: Locations
    - :name: headquarters
      :label: Headquarters
    - :name: offices
      :label: Offices
:purpose:
  :label: Purpose
  :icon: business
  :attributes:
    - :name: motivation
      :label: Motivations
    - :name: goal
      :label: Goals
    - :name: obstacles
      :label: Obstacles
    - :name: risks
      :label: Risks
:politics:
  :label: Politics
  :icon: thumbs_up_down
  :attributes:
    - :name: allies
      :label: Allies
    - :name: enemies
      :label: Enemies
    - :name: rivals
      :label: Rivals
    - :name: clients
      :label: Clients
:inventory:
  :label: Inventory
  :icon: shopping_cart
  :attributes:
    - :name: inventory
      :label: Inventory
    - :name: equipment
      :label: Equipment
    - :name: key_items
      :label: Key items
    - :name: suppliers
      :label: Suppliers
:gallery:
  :label: Gallery
  :icon: photo_library
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
