:overview:
  :label: overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: item_type
      :label: Item Type
    - :name: description
      :label: Description
    - :name: universe_id
      :label: Universe
:looks:
  :label: Looks
  :icon: redeem
  :attributes:
    - :name: materials
      :label: Materials
    - :name: weight
      :label: Weight
:history:
  :label: History
  :icon: book
  :attributes:
    - :name: original_owners
      :label: Original Owners
    - :name: past_owners
      :label: Past Owners
    - :name: current_owners
      :label: Current Owners
    - :name: makers
      :label: Makers
    - :name: year_made
      :label: Year it was made
:abilities:
  :label: Abilities
  :icon: flash_on
  :attributes:
    - :name: magic
      :label: Magic
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
