:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other names
    - :name: universe_id
      :label: Universe
:location:
  :label: Whereabouts
  :icon: location_on
  :attributes:
    - :name: countries
      :label: Country
    - :name: nearby_towns
      :label: Nearby towns
:appearance:
  :label: Appearance
  :icon: face
  :attributes:
    - :name: size
      :label: Size
    - :name: materials
      :label: Materials
    - :name: colors
      :label: Colors
:appearance:
  :label: Ecosystem
  :icon: local_florist
  :attributes:
    - :name: floras
      :label: Flora
    - :name: creatures
      :label: Creatures
:history:
  :label: History
  :icon: timeline
  :attributes:
    - :name: creation_story
      :label: Creation story
    - :name: established_year
      :label: Established year
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
