:overview:
  :label: overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: type_of
      :label: Type
    - :name: description
      :label: Description
    - :name: universe_id
      :label: Universe
:culture:
  :label: Culture
  :icon: face
  :attributes:
    - :name: leaders
      :label: Leaders
    - :name: population
      :label: Population
    - :name: language
      :label: Language
    - :name: currency
      :label: Currency
    - :name: motto
      :label: Motto
    - :name: laws
      :label: Laws
    - :name: sports
      :label: Sports
:cities:
  :label: Cities
  :icon: business
  :attributes:
    - :name: capital_cities
      :label: Capital Cities
    - :name: largest_cities
      :label: Largest Cities
    - :name: notable_cities
      :label: Notable Cities
:geography:
  :label: Geography
  :icon: map
  :attributes:
    - :name: area
      :label: Area
    - :name: crops
      :label: Crops
    - :name: located_at
      :label: Located At
    - :name: climate
      :label: Climate
:history:
  :label: History
  :icon: book
  :attributes:
    - :name: founding_story
      :label: Founding Story
    - :name: established_year
      :label: Established Year
    - :name: notable_wars
      :label: Notable Wars
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
