:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: role
      :label: Role
    - :name: aliases
      :label: Other names
    - :name: gender
      :label: Gender
    - :name: age
      :label: Age
    - :name: universe_id
      :label: Universe
:looks:
  :label: Looks
  :icon: face
  :attributes:
    - :name: weight
      :label: Weight
    - :name: height
      :label: Height
    - :name: haircolor
      :label: Hair Color
    - :name: hairstyle
      :label: Hair Style
    - :name: facialhair
      :label: Facial Hair
    - :name: eyecolor
      :label: Eye Color
    - :name: race
      :label: Race
    - :name: races
      :label: Linked Races
    - :name: skintone
      :label: Skin Tone
    - :name: bodytype
      :label: Body Type
    - :name: identmarks
      :label: Identifying Marks
:nature:
  :label: Nature
  :icon: fingerprint
  :attributes:
    - :name: mannerisms
      :label: Mannerisms
    - :name: motivations
      :label: Motivations
    - :name: flaws
      :label: Flaws
    - :name: prejudices
      :label: Prejudices
    - :name: talents
      :label: Talents
    - :name: hobbies
      :label: Hobbies
    - :name: personality_type
      :label: Personality Type
:social:
  :label: Social
  :icon: groups
  :attributes:
    - :name: spoken_languages
      :label: Languages spoken
    - :name: best_friends
      :label: Best Friends
    - :name: archenemies
      :label: Arch Enemies
    - :name: religion
      :label: Religion
    - :name: politics
      :label: Politics
    - :name: occupation
      :label: Occupation
    - :name: fave_color
      :label: Favorite Color
    - :name: fave_food
      :label: Favorite Food
    - :name: fave_possession
      :label: Favorite Possession
    - :name: fave_weapon
      :label: Favorite Weapon
    - :name: fave_animal
      :label: Favorite Animal
:history:
  :label: history
  :icon: info
  :attributes:
    - :name: birthday
      :label: Birthday
    - :name: birthplaces
      :label: Birthplaces
    - :name: education
      :label: Education
    - :name: background
      :label: Background
:family:
  :label: Family
  :icon: device_hub
  :attributes:
  - :name: mothers
    :label: Mothers
  - :name: fathers
    :label: Fathers
  - :name: spouses
    :label: Spouses
  - :name: love_interests
    :label: Love interests
  - :name: siblings
    :label: Siblings
  - :name: children
    :label: Children
  - :name: pets
    :label: Pets
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
