:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other names
    - :name: universe_id
      :label: Universe
:history:
  :label: History
  :icon: import_contacts
  :attributes:
    - :name: origin_story
      :label: Origin story
    - :name: notable_figures
      :label: Notable figures
    - :name: artifacts
      :label: Artifacts
:beliefs:
  :label: Beliefs
  :icon: forum
  :attributes:
    - :name: deities
      :label: Deities
    - :name: deity_characters
      :label: Deities
    - :name: teachings
      :label: Teachings
    - :name: prophecies
      :label: Prophecies
    - :name: places_of_worship
      :label: Places of worship
    - :name: worship_services
      :label: Worship services
    - :name: obligations
      :label: Obligations
    - :name: paradise
      :label: Vision of paradise
:traditions:
  :label: Traditions
  :icon: account_balance
  :attributes:
    - :name: initiation
      :label: Initiation process
    - :name: rituals
      :label: Rituals
    - :name: holidays
      :label: Holidays
:spread:
  :label: Spread
  :icon: location_on
  :attributes:
    - :name: practicing_locations
      :label: Practicing locations
    - :name: races
      :label: Practicing races
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
