:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: summary
      :label: Summary
    - :name: universe_id
      :label: Universe
:looks:
  :label: members
  :icon: face
  :attributes:
    - :name: scene_characters
      :label: Characters in scene
    - :name: scene_locations
      :label: Locations in scene
    - :name: scene_items
      :label: Items in scene
:action:
  :label: Action
  :icon: gesture
  :attributes:
    - :name: cause
      :label: What caused this?
    - :name: description
      :label: Description
    - :name: results
      :label: Results
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
