:overview:
  :label: overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: genre
      :label: Genre
:history:
  :label: History
  :icon: book
  :attributes:
    - :name: history
      :label: History
:rules:
  :label: Rules
  :icon: gavel
  :attributes:
    - :name: laws_of_physics
      :label: Laws of Physics
    - :name: magic_system
      :label: Magic System
    - :name: technologies
      :label: Technologies
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:settings:
  :label: Settings
  :icon: build
  :attributes:
    - :name: privacy
      :label: Privacy
:contributors:
  :label: Contributors
  :icon: group_add